from __future__ import annotations
from pathlib import Path
from decimal import Decimal
from typing import Union
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import LETTER
from reportlab.lib import colors
from reportlab.lib.units import inch
from .policy import Policy


def _fmt_money(value: Decimal) -> str:
    return f"{value.quantize(Decimal('0.01')):.2f}"


def generate_policy_pdf(policy: Policy, filename: Union[str, Path]) -> Path:
    """
    Generate a single-page PDF summarising the given Policy.
    Returns the Path to the created file.
    """
    out_path = Path(filename)
    c = canvas.Canvas(str(out_path), pagesize=LETTER)
    width, height = LETTER

    # Margins
    left = inch * 0.75
    right = width - inch * 0.75
    y = height - inch * 0.75

    # Header
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, y, "VEHICLE INSURANCE POLICY — SAMPLE DOCUMENT")
    y -= 24

    # Prominent fictional disclaimer
    disclaimer = "FICTIONAL SAMPLE — NOT A REAL INSURANCE CERTIFICATE"
    c.setFillColor(colors.red)
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(width / 2, y, disclaimer)
    c.setFillColor(colors.black)
    y -= 30

    # Subtitle clarifying demonstration-only nature
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width / 2, y, "This document is for demonstration purposes only and is not valid insurance.")
    y -= 28

    # Horizontal separator
    c.setLineWidth(0.5)
    c.line(left, y, right, y)
    y -= 18

    # Dynamic policy details (labels left, values right)
    c.setFont("Helvetica-Bold", 11)
    label_x = left
    value_x = right
    line_height = 16

    details = [
        ("Customer name", str(policy.customer_name)),
        ("Vehicle year", str(policy.vehicle_year)),
        ("Vehicle value", _fmt_money(Decimal(policy.vehicle_price))),
        ("Yearly premium", _fmt_money(Decimal(policy.yearly_premium))),
        ("Policy number", str(policy.policy_number)),
        ("Issue date", str(policy.issue_date)),
    ]

    c.setFont("Helvetica", 11)
    for label, val in details:
        c.drawString(label_x, y, f"{label}:")
        # right-align value by measuring string width
        text_width = c.stringWidth(val, "Helvetica", 11)
        c.drawString(value_x - text_width, y, val)
        y -= line_height

    y -= 6
    c.line(left, y, right, y)
    y -= 18

    # Static sample policy wording (kept short and clearly fictional)
    c.setFont("Helvetica", 10)
    text = (
        "Sample Coverage Summary (Fictional):\n"
        "This sample policy provides an illustrative summary of coverages and "
        "is provided for demonstration purposes only. It does not confer any "
        "insurance rights or obligations and should not be used as a real "
        "insurance certificate.\n\n"
        "For production use, replace this sample wording with formal policy "
        "documents prepared by licensed insurers."
    )

    # Draw multi-line text box
    text_obj = c.beginText()
    text_obj.setTextOrigin(left, y)
    text_obj.setLeading(14)
    for line in text.splitlines():
        text_obj.textLine(line)
    c.drawText(text_obj)

    # Footer small note
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width / 2, 0.5 * inch, "Document generated by sample Vehicle Insurance Policy Generator — fictional sample only.")

    # Finalize single page
    c.showPage()
    c.save()

    return out_path